import React, { useState } from 'react';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { Button } from '@mui/material';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import './styles/App.css';
import Form from './cmp/form';
import SignIn from './cmp/signin';
import ResetPassword from './cmp/resetPassword'; // Import ResetPassword component

const theme = createTheme({
  palette: {
    primary: {
      main: '#881c1c',
    },
  },
});

function App() {
  const [isStaff, setIsStaff] = useState(false);
  const handleStaffChange = () => setIsStaff(!isStaff);

  const searchParams = new URLSearchParams(window.location.search);
  const token = searchParams.get('token');

  let componentToRender;

  if (token) {
    componentToRender = <ResetPassword token={token} />;
  } else if (isStaff) {
    componentToRender = <SignIn />;
  } else {
    componentToRender = <Form />;
  }

  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <head>
        <title>URepair App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider theme={theme}>
        <main className="main">
          {/* <Nav staff={isStaff} onStaffChange={handleStaffChange}/> */}
          <div className="nav">
            <Button
              size="large"
              variant="contained"
              onClick={handleStaffChange}
              className="staffLogin"
            >
              {isStaff ? 'User' : 'Staff'}
              {' '}
              Login
            </Button>
          </div>
          {componentToRender}
        </main>
      </ThemeProvider>
    </LocalizationProvider>
  );
}

export default App;
